### ISSUE TITLE
Outbound link to original isslive.com website is dead -- domain is now squatted

### ISSUE THREAD

**Issue by SWGlassPit** [Lightstreamer/Lightstreamer-example-ISSLive-client-javascript#2]
Suggest updating links to the ISS Mimic project on github (https://github.com/ISS-Mimic/Mimic), which actively uses this data to drive a physical model of the ISS. The Mimic project also hosts a couple webpages displaying the telemetry streams directly in the browser: a list display with detailed descriptions at https://iss-mimic.github.io/Mimic/ as well as a dashboard style display that presents everything on one screen at https://iss-mimic.github.io/Mimic/dashboard.html.

**Comment by AlessandroAlinone** [comment]
Hey Tristan, thanks for this update on the Mimic project. I was in touch with Sam back in 2019 but I wasn't aware of the great results you have achieved now! We'll definitely update the links.

**Comment by AlessandroAlinone** [comment]
Removed the link to original isslive.com website. Added links to the Mimic Project in the "See Also" section.
